### ISSUE TITLE
Lazarus capsules TODO

### ISSUE THREAD

**Issue by difarem** [recordcrash/spacestation413#59]
- [ ] Don't allow mobs with a proper name to be renamed (will probably require a mob/living refactor)
- [ ] Relay audio from the capsule to the interior (maybe?)
- [ ] More detailed info about the contained mob when interacting with the capsule (HTML interface?)
